### PR TITLE
Updated Google Design

### PR DESCRIPTION
**Pull request by jensz12**
This should fix issue #2 
Except for the use of Roboto font, which has to be added by the end user
Edit: Can confirm that Google accepted this design as okay, after i changed the font to Roboto on the login button.

### CODE REVIEW

**Comment by splitbrain** [comment]
Can you please squash your changes into a single commit with a proper commit message? The SVG should be cleaned up and minimized (removing all unnecessary styles and attributes)

**Comment by splitbrain** [comment]
According to the branding guidelines, the "Sign in with Google" is not necessary:

> You can use the word "Google" by itself in the button if it is accompanied by adjacent text that makes it clear what the action is.

**Comment by jensz12** [comment]
Sure. Will fix the PR when I'm at my computer

**Comment by splitbrain** [comment]
@jensz12 any updates here?

**Pull request closed without merging**
